### ISSUE TITLE
Can't connect to steamdb

### ISSUE THREAD

**Issue by AbjectLlama** [ImaniiTy/GreenLuma-Reborn-Manager#10]
Hey I don't know why this is happening my friend says his is fine, this is what I get. It worked before so i'm not sure.

![GLR](https://user-images.githubusercontent.com/51475583/59090875-fe77f300-88db-11e9-8d98-bb7d3dbe1896.PNG)

[errors.log](https://github.com/ImaniiTy/GreenLuma-Reborn-Manager/files/3265057/errors.log)

**Comment by ImaniiTy** [comment]
Can you open steam.db in the browser?

**Comment by isaacay** [comment]
i am having the same issue and yes i am able to open https://steamdb.info/ in my browser

**Comment by ImaniiTy** [comment]
@AbjectLlama:
Try to install this program: [OpenSSL](https://slproweb.com/products/Win32OpenSSL.html), this should solve the error.

@isaacay:
Try to rename the folder where the executable is, I was having the same problem and this solved it (don't ask me why).

**Comment by AbjectLlama** [comment]
Hey the OpenSSL thing worked, thanks.

**Comment by PhantomLiberty** [comment]
I'm also having this issue.

SteamDB is still working in my browser. Installing OpenSSL and renaming the application's folder didn't fix it.

**Comment by ImaniiTy** [comment]
@PhantomLiberty can you upload your errors.log? (Sorry for the delay to reply, I had like 3 exams and 1 project this week)

**Comment by PhantomLiberty** [comment]
Didn't know there was an error log so I checked it and I fixed it myself. It wasn't recognizing my install of Lite in a custom location.  Installed the full version just in case and used the default install settings. Thanks for this useful tool. :)

**Comment by ImaniiTy** [comment]
you're welcome

**Comment by reboot89** [comment]
hi i had the issue where it says that i have to check internet connection
I then read here that it may be fixed if download and install the OpenSSL
I download and install light and full version
It fixed the check internet connection issue but it now says ''searching'' for a couple of seconds then it crashes and exit the program
Please help

**Comment by bigwillyman69** [comment]
> hi i had the issue where it says that i have to check internet connection
> I then read here that it may be fixed if download and install the OpenSSL
> I download and install light and full version
> It fixed the check internet connection issue but it now says ''searching'' for a couple of seconds then it crashes and exit the program
> Please help

I HAVE THE SAME PROBLEM!! PLEASE HELP!!!

**Comment by MaRsHaLaS** [comment]
[errors.log](https://github.com/ImaniiTy/GreenLuma-Reborn-Manager/files/5641805/errors.log)
Help me to fix

**Comment by busybox11** [comment]
Same here.

**Comment by Sadgedroid** [comment]
Same here. Everything works fine until I enter the name of a game. It starts searching, then crashes.

**Comment by ByFindIt152** [comment]
Same here xD
